# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# For the terminal to test
# xcodebuild clean build test \
#   -project Essentials-Network/Essentials-Network.xcodeproj/ \
#   -scheme "CI" \
#   -sdk macosx13.0 \
#   -destination "platform=macOS,arch=x86_64" \
#   CODE_SIGN_IDENTITY="" \
#   CODE_SIGNING_REQUIRED=NO

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app

    - name: Build and Test MacOS CI
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj/ -scheme "CI_macOS" -sdk macosx13.0 -destination "platform=macOS,arch=x86_64" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES

    - name: Build and Test iOS CI
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj/ -scheme "CI_iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
